{
 "title": "Fuse Camel Route Metrics",
 "description": "Default dashboard for Fuse",
 "tags": [ "1.0" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(org_apache_camel_ExchangesTotal, instance)"
   },
   {
    "name": "route",
    "label": "Route",
    "query": "label_values(org_apache_camel_ExchangesTotal, route)"
   }
  ]
 },
 "panels": [
  { "title": "Route ($route)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exchanges per second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(org_apache_camel_ExchangesTotal{instance=\"$instance\", route=\"\\\"$route\\\"\"}[5m])"
    }
   ]
  },
  {
   "title": "Exchanges inflight",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(org_apache_camel_ExchangesInflight{instance=\"$instance\", route=\"\\\"$route\\\"\"})"
    }
   ]
  },
  {
   "title": "Exchanges failure rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesFailed{instance=\"$instance\", route=\"\\\"$route\\\"\"}) / sum(org_apache_camel_ExchangesTotal{instance=\"$instance\", route=\"\\\"$route\\\"\"})"
    }
   ]
  },
  {
   "title": "Mean processing time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_MeanProcessingTime{instance=\"$instance\", route=\"\\\"$route\\\"\"}"
    }
   ]
  },
  {
   "title": "Exchanges per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_apache_camel_ExchangesFailed{instance=\"$instance\", route=\"\\\"$route\\\"\"}[5m])",
     "legendFormat": "Failed"
    },
    {
     "expr": "rate(org_apache_camel_ExchangesCompleted{instance=\"$instance\", route=\"\\\"$route\\\"\"}[5m])",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Exchanges inflight",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesInflight{instance=\"$instance\", route=\"\\\"$route\\\"\"}",
     "legendFormat": "Exchanges inflight"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "org_apache_camel_MaxProcessingTime{instance=\"$instance\", route=\"\\\"$route\\\"\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "org_apache_camel_MeanProcessingTime{instance=\"$instance\", route=\"\\\"$route\\\"\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "org_apache_camel_MinProcessingTime{instance=\"$instance\", route=\"\\\"$route\\\"\"}",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "External Redeliveries per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_apache_camel_ExternalRedeliveries{instance=\"$instance\", route=\"\\\"$route\\\"\"}[5m])"
    }
   ]
  },
  {
   "title": "Redeliveries per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_apache_camel_Redeliveries{instance=\"$instance\", route=\"\\\"$route\\\"\"}[5m])"
    }
   ]
  },
  {
   "title": "Failures handled per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_apache_camel_FailuresHandled{instance=\"$instance\", route=\"\\\"$route\\\"\"}[5m])"
    }
   ]
  }
 ]
}