{
 "title": "Fuse Camel Context Metrics",
 "description": "Fuse Metrics dashboard",
 "tags": [ "1.0" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(org_apache_camel_ExchangesTotal, instance)"
   },
   {
    "name": "context",
    "label": "Context",
    "query": "label_values(org_apache_camel_ExchangesTotal, context)"
   }
  ]
 },
 "panels": [
  {
   "title": "Process Start Time",
   "type": "singlestat",
   "description": "Process Start Time",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "description": "Memory currently being used by Fuse.",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "Threads",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{instance=\"$instance\"}",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "Camel Exchanges / 1m",
   "type": "graph",
   "description": "Camel Exchanges per minute",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(org_apache_camel_ExchangesCompleted{instance=\"$instance\", context=\"$context\"}[1m]))",
     "legendFormat": "Exchanges Completed / 1m"
    },
    {
     "expr": "sum(increase(org_apache_camel_ExchangesFailed{instance=\"$instance\", context=\"$context\"}[1m]))",
     "legendFormat": "Exchanges Failed / 1m"
    },
    {
     "expr": "sum(increase(org_apache_camel_ExchangesTotal{instance=\"$instance\", context=\"$context\"}[1m]))",
     "legendFormat": "Exchanges Total / 1m"
    },
    {
     "expr": "sum(org_apache_camel_ExchangesInflight{instance=\"$instance\", context=\"$context\"})",
     "legendFormat": "Exchanges Inflight"
    }
   ]
  },
  {
   "title": "Camel Processing Time",
   "type": "graph",
   "description": "Camel Processing Time",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_camel_DeltaProcessingTime{instance=\"$instance\", context=\"$context\"})",
     "legendFormat": "Delta Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_LastProcessingTime{instance=\"$instance\", context=\"$context\"})",
     "legendFormat": "Last Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_MaxProcessingTime{instance=\"$instance\", context=\"$context\"})",
     "legendFormat": "Max Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_MinProcessingTime{instance=\"$instance\", context=\"$context\"})",
     "legendFormat": "Min Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_MeanProcessingTime{instance=\"$instance\", context=\"$context\"})",
     "legendFormat": "Mean Processing Time"
    }
   ]
  },
  {
   "title": "Camel Service Durations",
   "type": "graph",
   "description": "Camel Service Durations",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_camel_MaxDuration{instance=\"$instance\", context=\"$context\"})",
     "legendFormat": "Maximum Duration"
    },
    {
     "expr": "sum(org_apache_camel_MinDuration{instance=\"$instance\", context=\"$context\"})",
     "legendFormat": "Minimum Duration"
    },
    {
     "expr": "sum(org_apache_camel_MeanDuration{instance=\"$instance\", context=\"$context\"})",
     "legendFormat": "Mean Duration"
    }
   ]
  },
  {
   "title": "Camel Failures & Redelivries",
   "type": "graph",
   "description": "Camel Failures & Redelivries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_camel_Redeliveries{instance=\"$instance\", context=\"$context\"})",
     "legendFormat": "Redeliveries"
    },
    {
     "expr": "sum(org_apache_camel_LastProcessingTime{instance=\"$instance\", context=\"$context\"})",
     "legendFormat": "Last Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_ExternalRedeliveries{instance=\"$instance\", context=\"$context\"})",
     "legendFormat": "External Redeliveries"
    }
   ]
  }
 ]
}