{
 "title": "Fuse Pod Metrics",
 "description": "Fuse Metrics dashboard",
 "tags": [ "1.0" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "label": "Pod", "query": "label_values(pod)" }
  ]
 },
 "panels": [
  {
   "title": "Process Start Time",
   "type": "singlestat",
   "description": "Process Start Time",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "description": "Memory currently being used by Fuse.",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{pod=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{pod=\"$pod\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed{pod=\"$pod\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{pod=\"$pod\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{pod=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "Threads",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod=\"$pod\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{pod=\"$pod\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{pod=\"$pod\"}",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "Camel Exchanges",
   "type": "graph",
   "description": "Camel Exchanges",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesCompleted{pod=\"$pod\"})",
     "legendFormat": "Exchanges Completed"
    },
    {
     "expr": "sum(org_apache_camel_ExchangesFailed{pod=\"$pod\"})",
     "legendFormat": "Exchanges Failed"
    },
    {
     "expr": "sum(org_apache_camel_ExchangesTotal{pod=\"$pod\"})",
     "legendFormat": "Exchanges Total"
    },
    {
     "expr": "sum(org_apache_camel_ExchangesInflight{pod=\"$pod\"})",
     "legendFormat": "Exchanges Inflight"
    }
   ]
  },
  {
   "title": "Camel Processing Time",
   "type": "graph",
   "description": "Camel Processing Time",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_camel_DeltaProcessingTime{pod=\"$pod\"})",
     "legendFormat": "Delta Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_LastProcessingTime{pod=\"$pod\"})",
     "legendFormat": "Last Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_MaxProcessingTime{pod=\"$pod\"})",
     "legendFormat": "Max Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_MinProcessingTime{pod=\"$pod\"})",
     "legendFormat": "Min Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_MeanProcessingTime{pod=\"$pod\"})",
     "legendFormat": "Mean Processing Time"
    }
   ]
  },
  {
   "title": "Camel Service Durations",
   "type": "graph",
   "description": "Camel Service Durations",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_camel_MaxDuration{pod=\"$pod\"})",
     "legendFormat": "Maximum Duration"
    },
    {
     "expr": "sum(org_apache_camel_MinDuration{pod=\"$pod\"})",
     "legendFormat": "Minimum Duration"
    },
    {
     "expr": "sum(org_apache_camel_MeanDuration{pod=\"$pod\"})",
     "legendFormat": "Mean Duration"
    }
   ]
  },
  {
   "title": "Camel Failures & Redelivries",
   "type": "graph",
   "description": "Camel Failures & Redelivries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_camel_Redeliveries{pod=\"$pod\"})",
     "legendFormat": "Redeliveries"
    },
    {
     "expr": "sum(org_apache_camel_LastProcessingTime{pod=\"$pod\"})",
     "legendFormat": "Last Processing Time"
    },
    {
     "expr": "sum(org_apache_camel_ExternalRedeliveries{pod=\"$pod\"})",
     "legendFormat": "External Redeliveries"
    }
   ]
  }
 ]
}